const                 { English messages } 
     msgNoExcel       = 'Excel cannot be lunched';
     msgNoConnect     = 'Excel not connected';
     msgNoLink        = 'Excel cannot linked';
     msgNoRespond     = 'Excel not responding';
     msgNoReply       = '*** No Reply ***';
     msgNotAccepted   ='" not accepted by Excel';
     msgNoMacro       = 'Macro is not opened';
     msgNoTable       = 'Table is not opened';

